"""create auth schema

Revision ID: 2c458fbc011b
Revises:
Create Date: 2026-07-29 12:30:47.819002

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2c458fbc011b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_counters',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_auth_rate_limit_counters_attempts_non_negative'),
    sa.CheckConstraint('length(key) > 0', name='ck_auth_rate_limit_counters_key_present'),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_index('ix_auth_rate_limit_counters_expiry', 'auth_rate_limit_counters', ['expires_at'], unique=False)
    op.create_table('auth_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'advisor', 'admin')", name='ck_auth_users_role'),
    sa.CheckConstraint("state IN ('pending_verification', 'temporary_password', 'active', 'disabled')", name='ck_auth_users_state'),
    sa.CheckConstraint('email = lower(email)', name='ck_auth_users_email_normalized'),
    sa.CheckConstraint('length(password_hash) > 0', name='ck_auth_users_password_hash_present'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_auth_users_email')
    )
    op.create_index('ix_auth_users_active_admins', 'auth_users', ['id'], unique=False, postgresql_where=sa.text("role = 'admin' AND state = 'active'"))
    op.create_table('auth_one_time_tokens',
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('email_verification', 'password_reset')", name='ck_auth_one_time_tokens_purpose'),
    sa.CheckConstraint('consumed_at IS NULL OR superseded_at IS NULL', name='ck_auth_one_time_tokens_single_terminal_state'),
    sa.CheckConstraint('expires_at > issued_at', name='ck_auth_one_time_tokens_expiry_after_issue'),
    sa.CheckConstraint('length(token_hash) > 0', name='ck_auth_one_time_tokens_hash_present'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name='fk_auth_one_time_tokens_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_auth_one_time_tokens_expiry', 'auth_one_time_tokens', ['expires_at'], unique=False)
    op.create_index('ix_auth_one_time_tokens_user_purpose', 'auth_one_time_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('auth_refresh_tokens',
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=32), nullable=True),
    sa.CheckConstraint("revocation_reason IS NULL OR revocation_reason IN ('logout', 'logout_all', 'rotated', 'replay_detected', 'password_reset', 'password_changed', 'account_disabled', 'admin_revoked')", name='ck_auth_refresh_tokens_revocation_reason'),
    sa.CheckConstraint('(revoked_at IS NULL) = (revocation_reason IS NULL)', name='ck_auth_refresh_tokens_revocation_paired'),
    sa.CheckConstraint('length(token_hash) > 0', name='ck_auth_refresh_tokens_hash_present'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name='fk_auth_refresh_tokens_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_auth_refresh_tokens_family', 'auth_refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_auth_refresh_tokens_family_expiry', 'auth_refresh_tokens', ['family_expires_at'], unique=False)
    op.create_index('ix_auth_refresh_tokens_session', 'auth_refresh_tokens', ['session_id'], unique=False)
    op.create_index('ix_auth_refresh_tokens_user', 'auth_refresh_tokens', ['user_id'], unique=False)
    op.create_table('auth_security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('length(event_type) > 0', name='ck_auth_security_events_type_present'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['auth_users.id'], name='fk_auth_security_events_actor', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_security_events_actor', 'auth_security_events', ['actor_user_id'], unique=False)
    op.create_index('ix_auth_security_events_occurred_at', 'auth_security_events', ['occurred_at'], unique=False)
    op.create_index('ix_auth_security_events_type', 'auth_security_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_security_events_type', table_name='auth_security_events')
    op.drop_index('ix_auth_security_events_occurred_at', table_name='auth_security_events')
    op.drop_index('ix_auth_security_events_actor', table_name='auth_security_events')
    op.drop_table('auth_security_events')
    op.drop_index('ix_auth_refresh_tokens_user', table_name='auth_refresh_tokens')
    op.drop_index('ix_auth_refresh_tokens_session', table_name='auth_refresh_tokens')
    op.drop_index('ix_auth_refresh_tokens_family_expiry', table_name='auth_refresh_tokens')
    op.drop_index('ix_auth_refresh_tokens_family', table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_index('ix_auth_one_time_tokens_user_purpose', table_name='auth_one_time_tokens')
    op.drop_index('ix_auth_one_time_tokens_expiry', table_name='auth_one_time_tokens')
    op.drop_table('auth_one_time_tokens')
    op.drop_index('ix_auth_users_active_admins', table_name='auth_users', postgresql_where=sa.text("role = 'admin' AND state = 'active'"))
    op.drop_table('auth_users')
    op.drop_index('ix_auth_rate_limit_counters_expiry', table_name='auth_rate_limit_counters')
    op.drop_table('auth_rate_limit_counters')
    # ### end Alembic commands ###
