"""tao bang locations

Revision ID: b44e204613af
Revises: 
Create Date: 2026-08-08 11:40:26.767165

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b44e204613af'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.String(length=64), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('province_id', sa.String(length=16), nullable=True),
    sa.Column('district_id', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('hotline', sa.String(length=64), nullable=True),
    sa.Column('directions_url', sa.Text(), nullable=True),
    sa.Column('open_time', sa.String(length=16), nullable=True),
    sa.Column('close_time', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_locations_city_district', 'locations', ['city', 'district'], unique=False)
    op.create_index('ix_locations_lat_lon', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_locations_type', 'locations', ['location_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locations_type', table_name='locations')
    op.drop_index('ix_locations_lat_lon', table_name='locations')
    op.drop_index('ix_locations_city_district', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
